version: '3.5'

services:
  my-ubuntu-os-01:
    build: .
    image: my-ubuntu-os
    container_name: my-ubuntu-os-01
    environment:
    - "TZ=Asia/Bangkok"
    tty: true
    volumes:
    - ./data:/data
    networks:
      my-ubuntu-network:
        ipv4_address: 10.1.254.2


#  my-ubuntu-os-02:
#    image: registry.gitlab.com/chanwit.kepha/my-ubuntu-os
#    container_name: my-ubuntu-os-02
#    tty: true
#    networks:
#      my-ubuntu-network:
#        ipv4_address: 172.22.0.3

networks:
  my-ubuntu-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.254.0/24
